server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/FindProject
    username: postgres
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update    # use 'validate' in production
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: tarfedof@gmail.com
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 782762664497-f6qfgobv8g8agoe3cetbo3k3ddkuht0t.apps.googleusercontent.com
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: [email, profile]
          github:
            client-id: Ov23liJtzhz2LWPXR9vS
            client-secret: ${GITHUB_CLIENT_SECRET}
            scope: [user:email]

  jackson:
    serialization:
      fail-on-empty-beans: false

logging:
  level:
    root: INFO
    org.springframework.security: INFO
    org.hibernate.SQL: DEBUG

app:
  name: FindProject
  mail:
    verify-url: http://localhost:8080/api/auth/verify
  jwt:
    secret: ${JWT_SECRET}
    expiration: 86400000   # 24h in ms